# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=pictures.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default='slug', unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
