# Generated by Django 2.1 on 2018-08-28 12:05

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=pictures.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=pictures.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=pictures.models.upload_image_path)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='images',
            name='picture',
            field=models.ForeignKey(on_delete=True, to='pictures.Pictures'),
        ),
    ]
